# example netlify.toml
[build]
  command = "npm run build --prod"
  functions = "netlify/functions"
  publish = "dist/hacker-news-client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
